---
title: "FPLab2"
author: 
  - Makayla Whitney
  - Joe Swinehart
  - Janette Avelar
  - David Fainstein
  date: "4/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lab 2 - Part A: Multiple Models
```{r initial code chunk}
file <- "https://github.com/datalorax/esvis/raw/master/data/benchmarks.rda"
load(url(file))
head(benchmarks)
```

```{r code chunk 2}
library(tidyverse)

benchmarks <- benchmarks %>%
	as_tibble() %>%
	mutate(wave = case_when(season == "Fall" ~ 0,
	                        season == "Winter" ~ 1,
	                        TRUE ~ 2))

by_sid <- split(benchmarks, benchmarks$sid)

perc <- map(by_sid, ~mutate(.x, percent = math / sid))

math_score <- map(perc, ~lm(math ~ wave, data = .x))
str(math_score)

coefs <- map(math_score, coef)
coefs[c(1:2, length(coefs))]

slopes <- map_dbl(coefs, 2)

slopes2 <- na.omit(slopes)

relation <- tibble(year = names(slopes2),
                   slope = slopes2)

ggplot(relation, aes(slope)) +
    geom_histogram(fill = "#87a96b",
                   color = "white", 
                   binwidth = 1) +
  labs(title = "Distribution of Student Math Scores",
       y = "") +
  geom_vline(xintercept = mean(slopes2),
             colour = "#FFE394", 
             size = 1.5)

```


## Lab 2 - Part B: Star Wars
```{r initial install}
#install.packages("repurrrsive")
library(repurrrsive)
library(magrittr)
library(naniar)

Characters_films <- sw_films %>% 
  map(list("characters")) %>% 
  map_dbl(~length(.x)) %>% 
  data.frame(movie = c(1:7),
             number_characters = .)

na_strings <- c("n/a", "none", "unknown")

Species_films <- sw_species %>% 
  map_dfr(extract, c("name", "hair_colors")) %>% 
  replace_with_na_all(condition = ~.x %in% na_strings) %>% 
  drop_na()
  
  
  
# Extra Code for future ideas / remembering what did NOT work
    # map(~mutate(.x, listnums = count("characters")))
  # map(summary) %>% 

```


## Lab 2 - Part C: Some basic API calls

```{r}
library(httr)
library(jsonlite)

# Abilities 1-5
abilities <-
map(1:5, ~content(GET(paste0("https://pokeapi.co/api/v2/ability/", .x)), "parsed"))

# Create data frame
names <- map_chr(abilities, ~.x$name)
counts <- map_dbl(abilities, ~length(.x$pokemon))
ability_sum <- data.frame(names, counts)
ability_sum
```

Bonus: Create a new data frame that lists the names of the pokemon with these specific abilities.

```{r Bonus}

```

